"""Initial commit

Revision ID: ce325c08d4d1
Revises: 
Create Date: 2021-05-01 15:45:44.077803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce325c08d4d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top250')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top250',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rating', sa.VARCHAR(length=10), nullable=True),
    sa.Column('year', sa.VARCHAR(length=10), nullable=True),
    sa.Column('votes', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rank', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
